application.env=prod

server.address=${MARKET_HOST}
server.port=80

security.jwt.secret-key=${MARKET_SECRET_KEY}
security.jwt.expiration-time=7200000

spring.datasource.url=jdbc:postgesql://${MARKET_DB_HOST}:${MARKET_DB_PORT}/${MARKET_DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
srpring.datasource.username=${MARKET_DB_USER}
spring.datasource.password=${MARKET_DB_PASS}
srping.jpa.hibernate.ddl-auto=validate
