application.env=prod

server.address=${EXCHANGE_HOST}
server.port=80

security.jwt.secret-key=placeholder
security.jwt.expiration-time=7200000

spring.datasource.url=jdbc:postgesql://${EXCHANGE_DB_HOST}:${EXCHANGE_DB_PORT}/${EXCHANGE_DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
srpring.datasource.username=${EXCHANGE_DB_USER}
spring.datasource.password=${EXCHANGE_DB_PASS}
srping.jpa.hibernate.ddl-auto=validate
