application.env=dev

security.jwt.secret-key=AtKiV4LDlZQlP2ZklvQ7yVOFudlc4swPimcXxP6AydB
security.jwt.expiration-time=7200000

spring.datasource.url=jdbc:postgresql://localhost:5432/market
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=market_user
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-dev.sql
spring.jpa.defer-datasource-initialization=true

logging.level.root=DEBUG
logging.level.org.springframework.security=DEBUG
