application.env=dev

security.jwt.secret-key=AtKiV4LDlZQlP2ZklvQ7yVOFudlc4swPimcXxP6AydB
security.jwt.expiration-time=7200000

spring.datasource.url=jdbc:postgresql://localhost:5432/exchange
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=exchange_user
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.data-locations=classpath:data-dev.sql
